### ISSUE TITLE
Where to flag issues of morpheus ?

### ISSUE THREAD

**Issue by drdhaval2785** [mbykov/morpheus#1]
@mbykov 
I see so many codes in your Github which are either morpheus or diglossa. 
I got confused where I should flag issues of morpheus (for Sanskrit language) for future development purpose.
This is the place where i thought I will put the issues.
Waiting for your nod.

I am working of generative aspect of pANini's grammar as you are working on analytical part.
subanta generation code - https://github.com/drdhaval2785/SanskritSubanta
subanta generation testing - http://lanover.com/lan/sanskrit/subanta.html
tiGanta generation code - https://github.com/drdhaval2785/SanskritVerb
tiGanta generation testing - http://www.lanover.com/lan/sanskrit/SanskritVerb/tiGanta.html

Dr Dhaval Patel
www.sanskritworld.in

**Comment by mbykov** [comment]
https://github.com/mbykov/morpheus.sa.js - Morpheus for Sanskrit is a best place, I hope. The rest are auxiliary repos. This repo, "morpheus" is old deprecated repo for latin and ancient greek, in Ruby. New repos are all in Javascript.

**Comment by drdhaval2785** [comment]
Great.
Will flag there.
