### ISSUE TITLE
Easily recognizable sandhi patterns

### ISSUE THREAD

**Issue by drdhaval2785** [mbykov/morpheus#2]
![capture](https://cloud.githubusercontent.com/assets/5755132/6764704/7dbfb7a2-cfe4-11e4-9a7e-e57c489c367b.png)

When I click on 'himAlayo' it doesn't give correct form.

It is very simple logic which can be deciphered by computer by regex.

When 'o-space-X' format is seen, it can be changed to 'H-space-X' format, because in most of the cases it is because of conversion of 'H' to 'o'.
X = h,y,v,r,l,Y,m,N,R,n,J,B,G,Q,D,j,b,g,q,d (Letters are in SLP1 transliteration)

In the present case it is 
'himAlayo nAma' has to be converted to 'himAlayaH nAma' and then analyse. We will get proper result.
 

I will try to enumerate such easy instances here.
We may ignore the difficult ones for the present.

**Comment by drdhaval2785** [comment]
Look at 'pfTivyA iva'
It actually is pfTivyAH iva.
The 'H' is elided because of sandhi.
That gives wrong interpretation that this is instrumental singular case of pfTivI.
![capture](https://cloud.githubusercontent.com/assets/5755132/6764812/5cf217ae-cfe9-11e4-9cad-936ea3274daa.png)

It has to be gen. singular.

Computational implication -
Look for 'a-space-vowel' / 'A-space-vowel' sequence. 
It is mostly because of elision of H.
Change them like this before processing.
'a-space-vowel' / 'A-space-vowel' -> 'aH-space-vowel' / 'AH-space-vowel'

e.g. pfTivyA iva -> pfTivyAH iva

**Comment by mbykov** [comment]
Mr. Patel, thank you. 

In this version only internal sandhi rules are activated. External ones will work only in version 2.0, I hope.  Alas, now Morpheus works only with stanalone wordforms. An architecture should be changed, so it will take some time.

**Comment by gasyoun** [comment]
@mbykov does what @drdhaval2785 wrote helps to understand how to simplify the logic? Have you read his paper on his generative logic based on Siddhanta Kaumudi?
