### ISSUE TITLE
Paradigms used for verb forms

### ISSUE THREAD

**Issue by drdhaval2785** [mbykov/morpheus#5]
It would be great if you share the paradigms which you have used to code for verb form analysis.

**Comment by mbykov** [comment]
Please look http://ru.diglossa.org:5984/_utils/index.html 

Select in last line "Rows per page" - 100 and then last DB - "seeds".
In "seeds" select view "flex" (right upper corner). Other views (flex-verb, flex-noun, etc do not  matter). Click on any row - this is source paradigm.

Look "View Code" (left upper corner) button for code of a view.

Main dicts DB for Morpheus is "sa". Select "sa" or "slp" views.

Please feel free to ask questions in case of any problem - CouchDB can be may be unusual for you

**Comment by drdhaval2785** [comment]
It seems from cursory reading that the method looks at the end of the word to find its paradigm.
But sometimes, the initial 'a' or 'A' are also important to catch e.g for certain verb forms like akArSIt, akarot etc.
